#include <string>
#include <iostream>
#include "stlfile.hpp"

static std::string inputFileName;
static std::string outputFileName;

void processTriangle (Triangle& trngl, StlOutBinFile& outFile) {
  V3
    s10     = trngl.vertices[1] - trngl.vertices[0],
    s20     = trngl.vertices[2] - trngl.vertices[0],
    normal  = s10.cross (s20),
    normal1 = normal * (1.0 / normal.norm());
  trngl.normal = normal1;
  outFile.writeTriangle (trngl);
}

int main (int argc, char *argv[])
{
  int trNum = 0;
  Triangle trngl0;
  V3 curNormal;
  double volume = 0;
  V3 pnt0;

  try {
    if (argc != 3) {
      std::cerr << " Usage : " << argv[0] << "  <input-file>  <output-file>" << std::endl;
      return 3;
    }
    inputFileName  = argv[1];
    outputFileName = argv[2];

    StlInFile     inFile  (inputFileName .c_str());
    StlOutBinFile outFile (outputFileName.c_str(), "Generated by \"stl-compute-normals\"");
    //    int numDclTrngl = inFile.numTriangles();
    // printf ("Declared %d triangles\n", numDclTrngl);

    inFile.readTriangle (trngl0);
    processTriangle     (trngl0, outFile);
    pnt0 = trngl0.vertices[0];

    for (trNum=1; ; trNum++) {
      Triangle trngl;
      if (! inFile.readTriangle (trngl))
          break;
      processTriangle (trngl,  outFile);                       
      M3 trianglePyramid (trngl.vertices[0] - pnt0,
                          trngl.vertices[1] - pnt0,
                          trngl.vertices[2] - pnt0);
      volume += trianglePyramid.det ();
    }
  }
  catch (std::string s) {
    std::cerr << " EXCEPTION : " << s << std::endl;
    std::cerr << " Last triangle number : " << trNum << std::endl;
    return 3;
  }
  volume /= 6;
  printf (" Volume : %lf\n", volume);
  return 0;
}
