#include <string>
#include <iostream>
#include "stlfile.hpp"

#include "stl-compute-normals.hpp"

int main (int argc, char *argv[])
{
  int trNum = 0;
  try {
    if (argc != 3) {
      std::cerr << " Usage : " << argv[0] << "  <input-file>  <output-file>" << std::endl;
      return 3;
    }
    StlInFile     inFile  (argv[1]);
    StlOutBinFile outFile (argv[2], "Generated by \"stl-compute-normals\"");
    for (trNum=0; ; trNum++) {
      Triangle trngl;
      if (! inFile.readTriangle (trngl))
          break;
      computeNormal (trngl);                       
      outFile.writeTriangle (trngl);
    }
  }
  catch (std::string s) {
    std::cerr << " EXCEPTION : " << s << std::endl;
    std::cerr << " Last triangle number : " << trNum << std::endl;
    return 3;
  }
  return 0;
}
